version: '3'
services:
  api:
    build: .
    container_name: api
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongodb:27017
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - /var/machine:/var/machine
      - /var/app:/var/app
    restart: unless-stopped
  mongodb:
    image: mongo:3.0
    container_name: mongodb
    expose:
      - 27017
