package models

// MachineConfig represetns config.json generated by docker-machine
type MachineConfig struct {
	Version float32 `json:"ConfigVersion"`
	Driver  struct {
		IPAddress string `json:"IPAddress"`
	} `json:"Driver"`
}
